version: '3'
services:
  app:
    build: .
    volumes:
      - ..:/workspace
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
